# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def common_Pods
    pod 'ZHMediator'
    pod 'ZHTableView'
    pod 'AVOSCloud'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'TZImagePickerController', '~>3.0.1'
    pod 'TZImagePreviewController'
    pod 'PGDatePicker'
    pod 'ReactiveObjC'
    pod 'Mantle'
    pod 'DateTools'
    pod 'MJRefresh', '~>3.1.14.1'
    pod 'mob_smssdk'
    pod 'MBProgressHUD'
    pod 'FMDB'
    pod 'YYText'
end

target 'ZHRemember' do
    common_Pods
    pod 'Google-Mobile-Ads-SDK'
end

target 'rememberPro' do
    common_Pods
end
