# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZHRemember' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ZHRemember
pod 'ZHMediator'
pod 'ZHTableView'
pod 'AVOSCloud'
pod 'SDWebImage'
pod 'Masonry'
pod 'TZImagePickerController'
pod 'PGDatePicker'
pod 'ReactiveObjC'
pod 'Mantle'
pod 'DateTools'
pod 'MJRefresh', '~>3.1.14.1'
pod 'mob_smssdk'
pod 'MBProgressHUD'
pod 'FMDB'

end
